### ISSUE TITLE
Help running Ethereum Benchmark

### ISSUE THREAD

**Issue by jamievaravara** [ooibc88/blockbench#18]
I am using Ubuntu 16.04.3 desktop 64-bit to run two virtual machines to test blockbench.

I am trying to run `./run-bench 1 1 1 1`, but i get this output:

https://pastebin.com/EC0JbWVR

And these are my variables in the env.sh file:

`ETH_HOME=/home/thesis/Documents/blockbench-master/benchmark/ethereum
HOSTS=$ETH_HOME/hosts
CLIENTS=$ETH_HOME/clients
ETH_DATA=/home/thesis/Documents/data
LOG_DIR=$ETH_HOME/donothing_donothingresults_1
EXE_HOME=/home/thesis/Documents/blockbench-master/src/smallbank/ycsb
BENCHMARK=ycsb

##comment these out for smallbank
#EXE_HOME=$ETH_HOME/../../src/smallbank/ethereum/ycsb
#BENCHMARK=smallbank`

I tried cloning the CustomGenesis.json to create a CustomGenesis_1.json file, but I still got the same output (invalid genesis file .... ), and I tried following the advice on this page [,](https://ethereum.stackexchange.com/questions/15283/getting-error-on-max-invalid-genesis-file-hex-string-has-odd-length), but to no help.

What am I doing wrong? What can I do?

**Comment by ug93tad** [comment]
how do you configure your VMs? Can they ping each other? Do they run SSH servers?

**Comment by jamievaravara** [comment]
I have them both running on NAT, and they can ping each other. Both of the VMs are running SSH servers.

**Comment by ug93tad** [comment]
what version of Ethereum are you running? the VMs with ...130 address is running your server?

**Comment by jamievaravara** [comment]
The ...129 address is running ethereum 1.8.4-stable
The ...130 address is running ethereum 1.8.2-stable

The ...129 address is the one I'm trying to run blockbench on,
and the ...130 address has an installation of etherum, installed trough the install.sh script in the blockbench/benchmark/ethereum directory.

They are both running ssh servers, and I can connect to each vm with ssh successfully.

**Comment by ArnChe** [comment]
I had the same problem. The field in extraData for Genesis_Files should be "extraData": "",  and not "extraData": "0x0",
Are your running from a local machine or do you run totally inside VMs? 
I'am currently working on this topic too

**Comment by ug93tad** [comment]
ok this is the problem with Ethereum version. 

In version 1.7.x, you need 0x in front, but maybe in 1.8.x it has been removed.

**Comment by johnslorid** [comment]
I have a similar issue, but I get this error after connecting through ssh and creating the genesis file:

`Fatal: Unable to attach to remote geth: dial unix` `//home/john/Documents/ethereum/privatechain/geth.ipc: connect: no such file or directory`
`Fatal: Unable to attach to remote geth: dial unix` `//home/john/Documents/ethereum/privatechain/geth.ipc: connect: no such file or directory`
`done node 192.168.187.130`

[Full output here:](https://pastebin.com/a1fp3EWM)

**Comment by jamievaravara** [comment]
Thanks for the help @ArnChe  ! It solved my issue. I have to change the value of the extraData fieled to "", but I didn't know that I had to change the genesis file in the VM that did not run the ./run-bench.sh script.

**Comment by jamievaravara** [comment]
I now have the same issue as @johnslorid though

**Comment by ArnChe** [comment]
@johnslorid and @jamievaravara as I suppose, you are using your local machine with /home/**username**/path/to/benchmark and an instance with Ubuntu, right? You have to determine the paths needed for the execution on your local machine and on the VMs. If shell should run on VM, pass a new directory like dir=directory/in/vm in front of the script.sh pointing to your directory in the VM. And I had to make another trick by gathering the enode adresses of the servers on my local machine and copy it to the right directory on server VMs via scp. That worked out for me. For the config files, have a look to the github repo of ethereum. Hope the explenation is understandable.

**Comment by jamievaravara** [comment]
thanks @ArnChe , I'm have changed the value of the ETH_DATA variable to /home/thesis/.ethereum, but the vm running run-bench.sh can still not find the geth.ipc folder for some reason.

**Comment by ArnChe** [comment]
Please chosse another path, because the .ethereum is a predefined folder for geth. What is the output of your addPeer.txt on the server after starting the test?

**Comment by jamievaravara** [comment]
the content of addPeer.txt is just admin.addPeer(). I believe nothing starts running, even though the genesis block is created, since it for some reason can not find the geth.ipc file.

**Comment by ArnChe** [comment]
That's the problem, your server/miner has to get information about all mining server in the network. You have to pass this addPeer.txt file to the mining server nodes. I start the framework from my local host, gather the enode addresses from server/mining nodes and pass it with scp to all mining nodes.

**Comment by keruisiya** [comment]
@johnslorid  @jamievaravara Hello, I have the same problem now, how do you solve this problem?
Fatal: Unable to attach to remote geth: dial unix
 //home/djs/Documents/ethereum/privatechain/geth.ipc: connect: no such file or directory
Fatal: Unable to attach to remote geth: dial unix 
//home/djs/Documents/ethereum/privatechain/geth.ipc:` connect: no such file or directory
done node 10.128.28.217

**Comment by yogesa** [comment]
![image](https://user-images.githubusercontent.com/30628588/195740234-f36c1ead-b7f7-4e4f-8bba-d0dd28bedfbd.png)
I want to know, the log result whether it is normal ? it show that result have some valid data, but some data it istill 0.
If it is normal, I want to understand why the result it is 0.

**Comment by tienquyet28** [comment]
> og result whether it is n

hi your log is normal due to the process of POW in ethereum it take sometime to approve your tx count so some =0 when POW is taking place, after done it will be count in polled block: right after that latency and request are counted as per respect to tx count
